### PR TITLE
Fix #53: Accessibility: input does not have an associated label 

### LINKED ISSUE #53: Accessibility: input does not have an associated label
**Describe the bug**
Axe accessibility testing reports the error "Form elements must have labels". While there is a label the for attrible has a differant ID to that of the input.

**To Reproduce**
1. Follow repo storybook example but without placeholder prop (as that prop stops Axe with another warning)

**Expected behavior**
The input should have a valid label for accessibility WCAG2A, and other standards

**Additional context**
The issue appears to be the result of the id of the input being set on input.tsx line 14. A change to `    const id = props.id` appears to resolve the issue, however I have not checked if there are adverse effects from that change.

### PR DESCRIPTION
**Pull request by tartan75**
closes #53
PR comprises 2 commits, one adding test, and the next providing fix.

### CODE REVIEW

File: src/components/Input/Input.tsx [hunk 1]
```diff
@@ -10,12 +10,10 @@ type InputProps = InputBaseComponentProps & {
...
   (props: InputProps, ref: React.ForwardedRef<HTMLInputElement>) => {
     const { text, isPlaceholder, placeholder, ...restInputProps } = props
-    // eslint-disable-next-line react/hook-use-state
-    const id = React.useId()
 
     return (
-      <Styled.Label htmlFor={id}>
-        <input {...restInputProps} ref={ref} id={id} />
+      <Styled.Label htmlFor={props.id}>
+        <input {...restInputProps} ref={ref} id={props.id} />
```
Comment (viclafouch) [inline src/components/Input/Input.tsx]: `restInputProps` should already set the id

Comment (tartan75) [reply src/components/Input/Input.tsx]: @viclafouch Thanks for that. Further commit pushed tidies this away.
